### ISSUE TITLE
Contribution in updating the website

### ISSUE THREAD

**Issue by at-the-vr** [nikhilsharma26500/portfolio-website#1]
**Description:** Adding Hover Effect -- Color CSS for Social Media Icons 
### Exemplar Screenshot -- 
![image](https://user-images.githubusercontent.com/88548999/216786217-ba079c57-de5f-4e19-9ea1-b50ee3082e20.png) ![image](https://user-images.githubusercontent.com/88548999/216786540-a5d379b0-7de3-48a9-8191-62e7d6613e92.png) ![image](https://user-images.githubusercontent.com/88548999/216786569-4869e5fe-ad45-4a07-9b7b-46f689712680.png)

**Extra Information**: Color used are referenced from Navbar component only.

**Comment by nikhilsharma26500** [comment]
Oh that's a cool addition, however, how about trying your hands on making the website's front page responsive? You can use CSS Bootstrap for that. That would be a good addition to your skillset.

Check the read.me section of the project to find out the bootstrap version  that I have used for my website.

**Comment by at-the-vr** [comment]
Sounds good to me would get started on immediately 😉
